services:
    csv.encoder:
        class: Symfony\Component\Serializer\Encoder\CsvEncoder

    serializer.csv_decoder:
        class: Symfony\Component\Serializer\Serializer
        arguments: [[]['@csv.encoder']]

    beer.trip_service:
        class: BeerBundle\Service\TripService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@beer.distance_service'

    beer.beer_service:
        class: BeerBundle\Service\BeerService
        arguments:
            - '@service_container'

    beer.distance_service:
        class: BeerBundle\Service\DistanceService
